development:
  adapter: postgresql
  encoding: unicode
  database: spotidora_sharkcloud_development
  pool: 5
  username:
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: spotidora_sharkcloud_test
  pool: 5
  username:
  password:
